services:
  mongo:
    image: mongo:6.0
    container_name: mongo_db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: carsdb
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: {}